# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shenanigans.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shenanigans.proto',
  package='shenanigans',
  serialized_pb='\n\x11shenanigans.proto\x12\x0bshenanigans\"\x86\x02\n\nSubmission\x12,\n\x05token\x18\x01 \x03(\x0b\x32\x1d.shenanigans.Submission.Token\x12\x31\n\x05group\x18\x02 \x03(\x0b\x32\".shenanigans.Submission.ProbeGroup\x1a\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x02(\x0c\x1a\x7f\n\nProbeGroup\x12\x0b\n\x03mac\x18\x01 \x01(\t\x12\x38\n\x03req\x18\x02 \x03(\x0b\x32+.shenanigans.Submission.ProbeGroup.ProbeReq\x1a*\n\x08ProbeReq\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08reqBytes\x18\x02 \x02(\x0c\x42\x02H\x03')




_SUBMISSION_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='shenanigans.Submission.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='shenanigans.Submission.Token.token', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=146,
  serialized_end=168,
)

_SUBMISSION_PROBEGROUP_PROBEREQ = _descriptor.Descriptor(
  name='ProbeReq',
  full_name='shenanigans.Submission.ProbeGroup.ProbeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='shenanigans.Submission.ProbeGroup.ProbeReq.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reqBytes', full_name='shenanigans.Submission.ProbeGroup.ProbeReq.reqBytes', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=255,
  serialized_end=297,
)

_SUBMISSION_PROBEGROUP = _descriptor.Descriptor(
  name='ProbeGroup',
  full_name='shenanigans.Submission.ProbeGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac', full_name='shenanigans.Submission.ProbeGroup.mac', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req', full_name='shenanigans.Submission.ProbeGroup.req', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SUBMISSION_PROBEGROUP_PROBEREQ, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=170,
  serialized_end=297,
)

_SUBMISSION = _descriptor.Descriptor(
  name='Submission',
  full_name='shenanigans.Submission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='shenanigans.Submission.token', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group', full_name='shenanigans.Submission.group', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SUBMISSION_TOKEN, _SUBMISSION_PROBEGROUP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=297,
)

_SUBMISSION_TOKEN.containing_type = _SUBMISSION;
_SUBMISSION_PROBEGROUP_PROBEREQ.containing_type = _SUBMISSION_PROBEGROUP;
_SUBMISSION_PROBEGROUP.fields_by_name['req'].message_type = _SUBMISSION_PROBEGROUP_PROBEREQ
_SUBMISSION_PROBEGROUP.containing_type = _SUBMISSION;
_SUBMISSION.fields_by_name['token'].message_type = _SUBMISSION_TOKEN
_SUBMISSION.fields_by_name['group'].message_type = _SUBMISSION_PROBEGROUP
DESCRIPTOR.message_types_by_name['Submission'] = _SUBMISSION

class Submission(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Token(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SUBMISSION_TOKEN

    # @@protoc_insertion_point(class_scope:shenanigans.Submission.Token)

  class ProbeGroup(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType

    class ProbeReq(_message.Message):
      __metaclass__ = _reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _SUBMISSION_PROBEGROUP_PROBEREQ

      # @@protoc_insertion_point(class_scope:shenanigans.Submission.ProbeGroup.ProbeReq)
    DESCRIPTOR = _SUBMISSION_PROBEGROUP

    # @@protoc_insertion_point(class_scope:shenanigans.Submission.ProbeGroup)
  DESCRIPTOR = _SUBMISSION

  # @@protoc_insertion_point(class_scope:shenanigans.Submission)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003')
# @@protoc_insertion_point(module_scope)
