// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shenanigans.proto

package io.shenanigans.proto;

public final class Shenanigans {
  private Shenanigans() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SubmissionOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;
    /**
     * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
     */
    java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup> 
        getGroupList();
    /**
     * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
     */
    io.shenanigans.proto.Shenanigans.Submission.ProbeGroup getGroup(int index);
    /**
     * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
     */
    int getGroupCount();
  }
  /**
   * Protobuf type {@code io.shenanigans.proto.Submission}
   */
  public static final class Submission extends
      com.google.protobuf.GeneratedMessageLite
      implements SubmissionOrBuilder {
    // Use Submission.newBuilder() to construct.
    private Submission(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Submission(boolean noInit) {}

    private static final Submission defaultInstance;
    public static Submission getDefaultInstance() {
      return defaultInstance;
    }

    public Submission getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Submission(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                group_ = new java.util.ArrayList<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup>();
                mutable_bitField0_ |= 0x00000001;
              }
              group_.add(input.readMessage(io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          group_ = java.util.Collections.unmodifiableList(group_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Submission> PARSER =
        new com.google.protobuf.AbstractParser<Submission>() {
      public Submission parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Submission(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Submission> getParserForType() {
      return PARSER;
    }

    public interface ProbeGroupOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {

      // optional string mac = 1;
      /**
       * <code>optional string mac = 1;</code>
       */
      boolean hasMac();
      /**
       * <code>optional string mac = 1;</code>
       */
      java.lang.String getMac();
      /**
       * <code>optional string mac = 1;</code>
       */
      com.google.protobuf.ByteString
          getMacBytes();

      // optional string token = 2;
      /**
       * <code>optional string token = 2;</code>
       */
      boolean hasToken();
      /**
       * <code>optional string token = 2;</code>
       */
      java.lang.String getToken();
      /**
       * <code>optional string token = 2;</code>
       */
      com.google.protobuf.ByteString
          getTokenBytes();

      // repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
       */
      java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq> 
          getReqList();
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
       */
      io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq getReq(int index);
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
       */
      int getReqCount();
    }
    /**
     * Protobuf type {@code io.shenanigans.proto.Submission.ProbeGroup}
     */
    public static final class ProbeGroup extends
        com.google.protobuf.GeneratedMessageLite
        implements ProbeGroupOrBuilder {
      // Use ProbeGroup.newBuilder() to construct.
      private ProbeGroup(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private ProbeGroup(boolean noInit) {}

      private static final ProbeGroup defaultInstance;
      public static ProbeGroup getDefaultInstance() {
        return defaultInstance;
      }

      public ProbeGroup getDefaultInstanceForType() {
        return defaultInstance;
      }

      private ProbeGroup(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                mac_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                token_ = input.readBytes();
                break;
              }
              case 26: {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  req_ = new java.util.ArrayList<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq>();
                  mutable_bitField0_ |= 0x00000004;
                }
                req_.add(input.readMessage(io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            req_ = java.util.Collections.unmodifiableList(req_);
          }
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<ProbeGroup> PARSER =
          new com.google.protobuf.AbstractParser<ProbeGroup>() {
        public ProbeGroup parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProbeGroup(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ProbeGroup> getParserForType() {
        return PARSER;
      }

      public interface ProbeReqOrBuilder
          extends com.google.protobuf.MessageLiteOrBuilder {

        // optional string ssid = 1;
        /**
         * <code>optional string ssid = 1;</code>
         */
        boolean hasSsid();
        /**
         * <code>optional string ssid = 1;</code>
         */
        java.lang.String getSsid();
        /**
         * <code>optional string ssid = 1;</code>
         */
        com.google.protobuf.ByteString
            getSsidBytes();

        // required bytes reqBytes = 2;
        /**
         * <code>required bytes reqBytes = 2;</code>
         */
        boolean hasReqBytes();
        /**
         * <code>required bytes reqBytes = 2;</code>
         */
        com.google.protobuf.ByteString getReqBytes();
      }
      /**
       * Protobuf type {@code io.shenanigans.proto.Submission.ProbeGroup.ProbeReq}
       */
      public static final class ProbeReq extends
          com.google.protobuf.GeneratedMessageLite
          implements ProbeReqOrBuilder {
        // Use ProbeReq.newBuilder() to construct.
        private ProbeReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
          super(builder);

        }
        private ProbeReq(boolean noInit) {}

        private static final ProbeReq defaultInstance;
        public static ProbeReq getDefaultInstance() {
          return defaultInstance;
        }

        public ProbeReq getDefaultInstanceForType() {
          return defaultInstance;
        }

        private ProbeReq(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          initFields();
          int mutable_bitField0_ = 0;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(input,
                                         extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  ssid_ = input.readBytes();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  reqBytes_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
          } finally {
            makeExtensionsImmutable();
          }
        }
        public static com.google.protobuf.Parser<ProbeReq> PARSER =
            new com.google.protobuf.AbstractParser<ProbeReq>() {
          public ProbeReq parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new ProbeReq(input, extensionRegistry);
          }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<ProbeReq> getParserForType() {
          return PARSER;
        }

        private int bitField0_;
        // optional string ssid = 1;
        public static final int SSID_FIELD_NUMBER = 1;
        private java.lang.Object ssid_;
        /**
         * <code>optional string ssid = 1;</code>
         */
        public boolean hasSsid() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public java.lang.String getSsid() {
          java.lang.Object ref = ssid_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              ssid_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string ssid = 1;</code>
         */
        public com.google.protobuf.ByteString
            getSsidBytes() {
          java.lang.Object ref = ssid_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            ssid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        // required bytes reqBytes = 2;
        public static final int REQBYTES_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString reqBytes_;
        /**
         * <code>required bytes reqBytes = 2;</code>
         */
        public boolean hasReqBytes() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes reqBytes = 2;</code>
         */
        public com.google.protobuf.ByteString getReqBytes() {
          return reqBytes_;
        }

        private void initFields() {
          ssid_ = "";
          reqBytes_ = com.google.protobuf.ByteString.EMPTY;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;

          if (!hasReqBytes()) {
            memoizedIsInitialized = 0;
            return false;
          }
          memoizedIsInitialized = 1;
          return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeBytes(1, getSsidBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeBytes(2, reqBytes_);
          }
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;

          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(1, getSsidBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(2, reqBytes_);
          }
          memoizedSerializedSize = size;
          return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }

        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        /**
         * Protobuf type {@code io.shenanigans.proto.Submission.ProbeGroup.ProbeReq}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
              io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq, Builder>
            implements io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReqOrBuilder {
          // Construct using io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private void maybeForceBuilderInitialization() {
          }
          private static Builder create() {
            return new Builder();
          }

          public Builder clear() {
            super.clear();
            ssid_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            reqBytes_ = com.google.protobuf.ByteString.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
          }

          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }

          public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq getDefaultInstanceForType() {
            return io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq.getDefaultInstance();
          }

          public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq build() {
            io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq buildPartial() {
            io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq result = new io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.ssid_ = ssid_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.reqBytes_ = reqBytes_;
            result.bitField0_ = to_bitField0_;
            return result;
          }

          public Builder mergeFrom(io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq other) {
            if (other == io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq.getDefaultInstance()) return this;
            if (other.hasSsid()) {
              bitField0_ |= 0x00000001;
              ssid_ = other.ssid_;
              
            }
            if (other.hasReqBytes()) {
              setReqBytes(other.getReqBytes());
            }
            return this;
          }

          public final boolean isInitialized() {
            if (!hasReqBytes()) {
              
              return false;
            }
            return true;
          }

          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq) e.getUnfinishedMessage();
              throw e;
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          // optional string ssid = 1;
          private java.lang.Object ssid_ = "";
          /**
           * <code>optional string ssid = 1;</code>
           */
          public boolean hasSsid() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          /**
           * <code>optional string ssid = 1;</code>
           */
          public java.lang.String getSsid() {
            java.lang.Object ref = ssid_;
            if (!(ref instanceof java.lang.String)) {
              java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
              ssid_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string ssid = 1;</code>
           */
          public com.google.protobuf.ByteString
              getSsidBytes() {
            java.lang.Object ref = ssid_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              ssid_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string ssid = 1;</code>
           */
          public Builder setSsid(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            ssid_ = value;
            
            return this;
          }
          /**
           * <code>optional string ssid = 1;</code>
           */
          public Builder clearSsid() {
            bitField0_ = (bitField0_ & ~0x00000001);
            ssid_ = getDefaultInstance().getSsid();
            
            return this;
          }
          /**
           * <code>optional string ssid = 1;</code>
           */
          public Builder setSsidBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            ssid_ = value;
            
            return this;
          }

          // required bytes reqBytes = 2;
          private com.google.protobuf.ByteString reqBytes_ = com.google.protobuf.ByteString.EMPTY;
          /**
           * <code>required bytes reqBytes = 2;</code>
           */
          public boolean hasReqBytes() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          /**
           * <code>required bytes reqBytes = 2;</code>
           */
          public com.google.protobuf.ByteString getReqBytes() {
            return reqBytes_;
          }
          /**
           * <code>required bytes reqBytes = 2;</code>
           */
          public Builder setReqBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            reqBytes_ = value;
            
            return this;
          }
          /**
           * <code>required bytes reqBytes = 2;</code>
           */
          public Builder clearReqBytes() {
            bitField0_ = (bitField0_ & ~0x00000002);
            reqBytes_ = getDefaultInstance().getReqBytes();
            
            return this;
          }

          // @@protoc_insertion_point(builder_scope:io.shenanigans.proto.Submission.ProbeGroup.ProbeReq)
        }

        static {
          defaultInstance = new ProbeReq(true);
          defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:io.shenanigans.proto.Submission.ProbeGroup.ProbeReq)
      }

      private int bitField0_;
      // optional string mac = 1;
      public static final int MAC_FIELD_NUMBER = 1;
      private java.lang.Object mac_;
      /**
       * <code>optional string mac = 1;</code>
       */
      public boolean hasMac() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string mac = 1;</code>
       */
      public java.lang.String getMac() {
        java.lang.Object ref = mac_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mac_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string mac = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMacBytes() {
        java.lang.Object ref = mac_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string token = 2;
      public static final int TOKEN_FIELD_NUMBER = 2;
      private java.lang.Object token_;
      /**
       * <code>optional string token = 2;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;
      public static final int REQ_FIELD_NUMBER = 3;
      private java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq> req_;
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
       */
      public java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq> getReqList() {
        return req_;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
       */
      public java.util.List<? extends io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReqOrBuilder> 
          getReqOrBuilderList() {
        return req_;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
       */
      public int getReqCount() {
        return req_.size();
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
       */
      public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq getReq(int index) {
        return req_.get(index);
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
       */
      public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReqOrBuilder getReqOrBuilder(
          int index) {
        return req_.get(index);
      }

      private void initFields() {
        mac_ = "";
        token_ = "";
        req_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        for (int i = 0; i < getReqCount(); i++) {
          if (!getReq(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMacBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTokenBytes());
        }
        for (int i = 0; i < req_.size(); i++) {
          output.writeMessage(3, req_.get(i));
        }
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMacBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTokenBytes());
        }
        for (int i = 0; i < req_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, req_.get(i));
        }
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(io.shenanigans.proto.Shenanigans.Submission.ProbeGroup prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code io.shenanigans.proto.Submission.ProbeGroup}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            io.shenanigans.proto.Shenanigans.Submission.ProbeGroup, Builder>
          implements io.shenanigans.proto.Shenanigans.Submission.ProbeGroupOrBuilder {
        // Construct using io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          mac_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          token_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          req_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup getDefaultInstanceForType() {
          return io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.getDefaultInstance();
        }

        public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup build() {
          io.shenanigans.proto.Shenanigans.Submission.ProbeGroup result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup buildPartial() {
          io.shenanigans.proto.Shenanigans.Submission.ProbeGroup result = new io.shenanigans.proto.Shenanigans.Submission.ProbeGroup(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.mac_ = mac_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.token_ = token_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            req_ = java.util.Collections.unmodifiableList(req_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.req_ = req_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(io.shenanigans.proto.Shenanigans.Submission.ProbeGroup other) {
          if (other == io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.getDefaultInstance()) return this;
          if (other.hasMac()) {
            bitField0_ |= 0x00000001;
            mac_ = other.mac_;
            
          }
          if (other.hasToken()) {
            bitField0_ |= 0x00000002;
            token_ = other.token_;
            
          }
          if (!other.req_.isEmpty()) {
            if (req_.isEmpty()) {
              req_ = other.req_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureReqIsMutable();
              req_.addAll(other.req_);
            }
            
          }
          return this;
        }

        public final boolean isInitialized() {
          for (int i = 0; i < getReqCount(); i++) {
            if (!getReq(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.shenanigans.proto.Shenanigans.Submission.ProbeGroup parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.shenanigans.proto.Shenanigans.Submission.ProbeGroup) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string mac = 1;
        private java.lang.Object mac_ = "";
        /**
         * <code>optional string mac = 1;</code>
         */
        public boolean hasMac() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string mac = 1;</code>
         */
        public java.lang.String getMac() {
          java.lang.Object ref = mac_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            mac_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string mac = 1;</code>
         */
        public com.google.protobuf.ByteString
            getMacBytes() {
          java.lang.Object ref = mac_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            mac_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string mac = 1;</code>
         */
        public Builder setMac(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          mac_ = value;
          
          return this;
        }
        /**
         * <code>optional string mac = 1;</code>
         */
        public Builder clearMac() {
          bitField0_ = (bitField0_ & ~0x00000001);
          mac_ = getDefaultInstance().getMac();
          
          return this;
        }
        /**
         * <code>optional string mac = 1;</code>
         */
        public Builder setMacBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          mac_ = value;
          
          return this;
        }

        // optional string token = 2;
        private java.lang.Object token_ = "";
        /**
         * <code>optional string token = 2;</code>
         */
        public boolean hasToken() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public java.lang.String getToken() {
          java.lang.Object ref = token_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            token_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTokenBytes() {
          java.lang.Object ref = token_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            token_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public Builder setToken(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          token_ = value;
          
          return this;
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public Builder clearToken() {
          bitField0_ = (bitField0_ & ~0x00000002);
          token_ = getDefaultInstance().getToken();
          
          return this;
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public Builder setTokenBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          token_ = value;
          
          return this;
        }

        // repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;
        private java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq> req_ =
          java.util.Collections.emptyList();
        private void ensureReqIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            req_ = new java.util.ArrayList<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq>(req_);
            bitField0_ |= 0x00000004;
           }
        }

        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq> getReqList() {
          return java.util.Collections.unmodifiableList(req_);
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public int getReqCount() {
          return req_.size();
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq getReq(int index) {
          return req_.get(index);
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder setReq(
            int index, io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqIsMutable();
          req_.set(index, value);

          return this;
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder setReq(
            int index, io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq.Builder builderForValue) {
          ensureReqIsMutable();
          req_.set(index, builderForValue.build());

          return this;
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder addReq(io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqIsMutable();
          req_.add(value);

          return this;
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder addReq(
            int index, io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqIsMutable();
          req_.add(index, value);

          return this;
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder addReq(
            io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq.Builder builderForValue) {
          ensureReqIsMutable();
          req_.add(builderForValue.build());

          return this;
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder addReq(
            int index, io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq.Builder builderForValue) {
          ensureReqIsMutable();
          req_.add(index, builderForValue.build());

          return this;
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder addAllReq(
            java.lang.Iterable<? extends io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.ProbeReq> values) {
          ensureReqIsMutable();
          super.addAll(values, req_);

          return this;
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder clearReq() {
          req_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);

          return this;
        }
        /**
         * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup.ProbeReq req = 3;</code>
         */
        public Builder removeReq(int index) {
          ensureReqIsMutable();
          req_.remove(index);

          return this;
        }

        // @@protoc_insertion_point(builder_scope:io.shenanigans.proto.Submission.ProbeGroup)
      }

      static {
        defaultInstance = new ProbeGroup(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:io.shenanigans.proto.Submission.ProbeGroup)
    }

    // repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;
    public static final int GROUP_FIELD_NUMBER = 1;
    private java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup> group_;
    /**
     * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
     */
    public java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup> getGroupList() {
      return group_;
    }
    /**
     * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
     */
    public java.util.List<? extends io.shenanigans.proto.Shenanigans.Submission.ProbeGroupOrBuilder> 
        getGroupOrBuilderList() {
      return group_;
    }
    /**
     * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
     */
    public int getGroupCount() {
      return group_.size();
    }
    /**
     * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
     */
    public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup getGroup(int index) {
      return group_.get(index);
    }
    /**
     * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
     */
    public io.shenanigans.proto.Shenanigans.Submission.ProbeGroupOrBuilder getGroupOrBuilder(
        int index) {
      return group_.get(index);
    }

    private void initFields() {
      group_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getGroupCount(); i++) {
        if (!getGroup(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < group_.size(); i++) {
        output.writeMessage(1, group_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < group_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, group_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.shenanigans.proto.Shenanigans.Submission parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.shenanigans.proto.Shenanigans.Submission parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.shenanigans.proto.Shenanigans.Submission prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code io.shenanigans.proto.Submission}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.shenanigans.proto.Shenanigans.Submission, Builder>
        implements io.shenanigans.proto.Shenanigans.SubmissionOrBuilder {
      // Construct using io.shenanigans.proto.Shenanigans.Submission.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        group_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public io.shenanigans.proto.Shenanigans.Submission getDefaultInstanceForType() {
        return io.shenanigans.proto.Shenanigans.Submission.getDefaultInstance();
      }

      public io.shenanigans.proto.Shenanigans.Submission build() {
        io.shenanigans.proto.Shenanigans.Submission result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.shenanigans.proto.Shenanigans.Submission buildPartial() {
        io.shenanigans.proto.Shenanigans.Submission result = new io.shenanigans.proto.Shenanigans.Submission(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          group_ = java.util.Collections.unmodifiableList(group_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.group_ = group_;
        return result;
      }

      public Builder mergeFrom(io.shenanigans.proto.Shenanigans.Submission other) {
        if (other == io.shenanigans.proto.Shenanigans.Submission.getDefaultInstance()) return this;
        if (!other.group_.isEmpty()) {
          if (group_.isEmpty()) {
            group_ = other.group_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGroupIsMutable();
            group_.addAll(other.group_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getGroupCount(); i++) {
          if (!getGroup(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.shenanigans.proto.Shenanigans.Submission parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.shenanigans.proto.Shenanigans.Submission) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;
      private java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup> group_ =
        java.util.Collections.emptyList();
      private void ensureGroupIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          group_ = new java.util.ArrayList<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup>(group_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public java.util.List<io.shenanigans.proto.Shenanigans.Submission.ProbeGroup> getGroupList() {
        return java.util.Collections.unmodifiableList(group_);
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public int getGroupCount() {
        return group_.size();
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public io.shenanigans.proto.Shenanigans.Submission.ProbeGroup getGroup(int index) {
        return group_.get(index);
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder setGroup(
          int index, io.shenanigans.proto.Shenanigans.Submission.ProbeGroup value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder setGroup(
          int index, io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.Builder builderForValue) {
        ensureGroupIsMutable();
        group_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder addGroup(io.shenanigans.proto.Shenanigans.Submission.ProbeGroup value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.add(value);

        return this;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder addGroup(
          int index, io.shenanigans.proto.Shenanigans.Submission.ProbeGroup value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder addGroup(
          io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.Builder builderForValue) {
        ensureGroupIsMutable();
        group_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder addGroup(
          int index, io.shenanigans.proto.Shenanigans.Submission.ProbeGroup.Builder builderForValue) {
        ensureGroupIsMutable();
        group_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder addAllGroup(
          java.lang.Iterable<? extends io.shenanigans.proto.Shenanigans.Submission.ProbeGroup> values) {
        ensureGroupIsMutable();
        super.addAll(values, group_);

        return this;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder clearGroup() {
        group_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .io.shenanigans.proto.Submission.ProbeGroup group = 1;</code>
       */
      public Builder removeGroup(int index) {
        ensureGroupIsMutable();
        group_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.shenanigans.proto.Submission)
    }

    static {
      defaultInstance = new Submission(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.shenanigans.proto.Submission)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
